package Vista.components;

import Modelo.Sala;
import Vista.Aplication;
import Vista.ManagmentSala;
import Vista.utils.UIConfig;

public class ComponentSala extends javax.swing.JPanel {
    private Aplication JFPrincipal;
    private Sala sala;
    /**
     * Creates new form Sala
     */
    public ComponentSala(Sala sala, Aplication JF) {
        this.JFPrincipal = JF;
        this.sala = sala;
        initComponents();
        name.setText(sala.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new Vista.components.Title();
        jPanel2 = new javax.swing.JPanel();
        customButton1 = new Vista.components.CustomButton();

        setBackground(UIConfig.getBg(300)
        );
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        name.setText("Nombre De Sala");
        name.setAlignmentX(0.5F);
        jPanel1.add(name);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel1.add(jPanel2);

        customButton1.setText("Administrar");
        customButton1.setAlignmentX(0.5F);
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton1);

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        try {
            ManagmentSala MS = new ManagmentSala(sala, JFPrincipal);
            JFPrincipal.changeContent(MS);
        } catch (Exception e) {
            name.setText(e.getMessage());
        }
    }//GEN-LAST:event_customButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.components.CustomButton customButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private Vista.components.Title name;
    // End of variables declaration//GEN-END:variables
}
