package Vista.components;

import Modelo.Computador;
import Modelo.Sala;
import Modelo.Servicio;
import Vista.Aplication;
import Vista.ViewSalas;
import java.util.Map;
import org.json.JSONArray;

public class CreateComputers extends javax.swing.JPanel {
    private NameComputer[] arrayComp;
    private Sala newSala;
    private Aplication JF;
    
    public CreateComputers(Map<Integer, int[]> computersData, Sala newSala, Aplication JF) {
        this.JF = JF;
        initComponents();
        this.newSala = newSala;
        this.arrayComp = new NameComputer[computersData.size()];
        int i = 0;
        for (Map.Entry<Integer, int[]> entry : computersData.entrySet()) {
            int[] coordinates = entry.getValue();
            NameComputer nc = new NameComputer(entry.getKey());
            this.arrayComp[i] = nc;
            listComputers.add(nc);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listComputers = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        customButton1 = new Vista.components.CustomButton();

        setLayout(new java.awt.BorderLayout());

        listComputers.setLayout(new java.awt.GridLayout(8, 3));
        add(listComputers, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        customButton1.setText("Finalizar");
        customButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton1, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        Computador[] newComputers = new Computador[arrayComp.length];
        int i = 0;
        for (NameComputer name : arrayComp){
            newComputers[i] = new Computador(name.getText(), name.getNumber(), newSala.getId());
            System.out.println(name.getText());
            i++;
        }
        JSONArray body = new JSONArray(newComputers);
        Servicio.createComputers(body);
        Servicio.updateRooms();
        ViewSalas nvs = new ViewSalas(JF);
        JF.changeContent(nvs);
    }//GEN-LAST:event_customButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.components.CustomButton customButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel listComputers;
    // End of variables declaration//GEN-END:variables
}
