/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.components;

import Modelo.Servicio;
import Modelo.Sesion;
import Vista.AdministrarUsuarios;
import Vista.ManagmentSala;
import Vista.utils.UIConfig;

/**
 *
 * @author layonel
 */
public class ModalAddUser extends javax.swing.JDialog {

    /**
     * Creates new form ModalAddUser
     */
    private Object computer_id;
    private Integer sala_id;
    private ManagmentSala mgs;
    
    public ModalAddUser(Object computer_id, Integer sala_id, ManagmentSala mgs) {
        this.mgs = mgs;
        this.computer_id = computer_id;
        this.sala_id = sala_id;
        initComponents();
        newUser.setVisible(false);
        newUser.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1 = new Vista.components.Title();
        jPanel1 = new javax.swing.JPanel();
        customLabel1 = new Vista.components.CustomLabel();
        inputDocNumber = new Vista.components.CustomInput();
        customButton1 = new Vista.components.CustomButton("Cancelar", 2);
        customButton2 = new Vista.components.CustomButton("Añador", 1);
        jPanel2 = new javax.swing.JPanel();
        errorMessage = new Vista.components.CustomLabel();
        newUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(UIConfig.getBg(500)
        );
        setMinimumSize(new java.awt.Dimension(300, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 250));

        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Añadir Usuario");
        title1.setPreferredSize(new java.awt.Dimension(139, 37));
        getContentPane().add(title1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 90));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0, 10, 15));

        customLabel1.setText("Numero de Documento:");
        jPanel1.add(customLabel1);
        jPanel1.add(inputDocNumber);

        customButton1.setText("Cancelar");
        customButton1.setStyle(2);
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton1);

        customButton2.setText("Añadir");
        customButton2.setStyle(1);
        customButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        errorMessage.setForeground(new java.awt.Color(255, 51, 51));
        errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage.setText(" ");
        jPanel2.add(errorMessage);

        newUser.setText("Añadir Usuario");
        newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserActionPerformed(evt);
            }
        });
        jPanel2.add(newUser);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_customButton1ActionPerformed

    private void customButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton2ActionPerformed
        String docNumber = inputDocNumber.getText();
        newUser.setVisible(false);
        newUser.setEnabled(false);
        errorMessage.setText("...");
        if (docNumber.isEmpty()){
            errorMessage.setText("Se necesita un Numero de documento.");
            return;
        }
        System.out.println(docNumber);
        String new_computer_id = computer_id.toString();
        Sesion sesion =Servicio.addActiveSession(docNumber, sala_id, new_computer_id);
        
        if (sesion.getUsuario().getDocument_number() == 0){
            errorMessage.setText("No se ecnotró un usuario.");
            newUser.setVisible(true);
            newUser.setEnabled(true);
            return;
        }
        
        mgs.revalidate();
        mgs.repaint();
        mgs.updateUI();
        this.setVisible(false);
        errorMessage.setText("");
        this.dispose();
        mgs.update();
    }//GEN-LAST:event_customButton2ActionPerformed

    private void newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserActionPerformed
        AdministrarUsuarios AU = new AdministrarUsuarios();
        mgs.JFPrincipal.changeContent(AU);
        this.dispose();
    }//GEN-LAST:event_newUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.components.CustomButton customButton1;
    private Vista.components.CustomButton customButton2;
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomLabel errorMessage;
    private Vista.components.CustomInput inputDocNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton newUser;
    private Vista.components.Title title1;
    // End of variables declaration//GEN-END:variables
}
