package Vista.components;

public class NameComputer extends javax.swing.JPanel {
    int number;
    
    public NameComputer(int number) {
        initComponents();
        this.number = number;
        numberText.setText(String.valueOf(number));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        numberText = new Vista.components.Title();
        customLabel1 = new Vista.components.CustomLabel();
        nameInput = new Vista.components.CustomInput();

        setMinimumSize(new java.awt.Dimension(155, 10));
        setPreferredSize(new java.awt.Dimension(250, 50));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {20, 100, 200};
        setLayout(layout);

        numberText.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(numberText, gridBagConstraints);

        customLabel1.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(customLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(nameInput, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    public String getText(){
        if (nameInput.getText().isEmpty()){
            return  "Computador #" + this.number;
        }
        return nameInput.getText();
    }
    
    public int getNumber(){
        return number;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomInput nameInput;
    private Vista.components.Title numberText;
    // End of variables declaration//GEN-END:variables
}
