/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.components;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicComboBoxUI;
import Vista.utils.PanelRound;
import javax.swing.border.Border;

/**
 *
 * @author layonel
 */
public class Testing extends PanelRound {

    /**
     * Creates new form Testing
     */
    public Testing() {
        super();
        initComponents();
        jComboBox1.setUI(new BasicComboBoxUI() {
            @Override
            protected JButton createArrowButton() {
                JButton newArrowButton = super.createArrowButton();
                newArrowButton.setBackground(new Color(102, 255, 204)); // Cambia el color aquí
                newArrowButton.setBorder(null);
                newArrowButton.setContentAreaFilled(false);
                newArrowButton.setForeground(Color.black);
                newArrowButton.setOpaque(true);
                return newArrowButton;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jPanel3.setLayout(new java.awt.GridLayout());

        jLabel4.setText("Salas");
        jPanel3.add(jLabel4);

        jComboBox4.setBackground(new java.awt.Color(102, 255, 204));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setBorder(null);
        jPanel3.add(jComboBox4);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout());

        jLabel5.setText("Salas");
        jPanel4.add(jLabel5);

        jComboBox5.setBackground(new java.awt.Color(102, 255, 204));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setBorder(null);
        jPanel4.add(jComboBox5);

        jPanel1.add(jPanel4);

        jPanel2.setLayout(new java.awt.GridLayout());

        jLabel1.setText("Salas");
        jPanel2.add(jLabel1);

        jComboBox1.setBackground(new java.awt.Color(102, 255, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);
        jPanel2.add(jComboBox1);

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
