package Vista;

import Controlador.Usuarios.ConAU_BuscarUsuario;
import Controlador.Usuarios.ConAU_CrearUsuario;
import Vista.utils.UIConfig;

public class AdministrarUsuarios extends javax.swing.JPanel {

    public AdministrarUsuarios() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound3 = new Vista.utils.PanelRound();
        jButton1 = new Vista.components.CustomButton();
        panelRound2 = new Vista.utils.PanelRound();
        jButton2 = new Vista.components.CustomButton();
        contentAU = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        panelRound3.setBackground(UIConfig.getPrimaryColor(500)
        );
        panelRound3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);
        panelRound3.setLayout(new javax.swing.BoxLayout(panelRound3, javax.swing.BoxLayout.PAGE_AXIS));

        jButton1.setBackground(UIConfig.getPrimaryColor(500)
        );
        jButton1.setText("Búsqueda");
        jButton1.setAlignmentX(0.5F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound3.add(jButton1);

        jPanel1.add(panelRound3);

        panelRound2.setBackground(UIConfig.getPrimaryColor(500));
        panelRound2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new javax.swing.BoxLayout(panelRound2, javax.swing.BoxLayout.PAGE_AXIS));

        jButton2.setBackground(UIConfig.getPrimaryColor(500)
        );
        jButton2.setText("Añadir Usuario");
        jButton2.setAlignmentX(0.5F);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRound2.add(jButton2);

        jPanel1.add(panelRound2);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        contentAU.setFocusCycleRoot(true);
        contentAU.setOpaque(false);
        contentAU.setPreferredSize(new java.awt.Dimension(0, 0));
        contentAU.setLayout(new javax.swing.BoxLayout(contentAU, javax.swing.BoxLayout.X_AXIS));
        add(contentAU, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AU_BuscarUsuario BusUser = new AU_BuscarUsuario();
        ConAU_BuscarUsuario ConBUser = new ConAU_BuscarUsuario(BusUser);
        ConBUser.Inicio();
        
        contentAU.removeAll();
        contentAU.add(BusUser);
        contentAU.revalidate();
        contentAU.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AU_CrearUsuario CreateUser = new AU_CrearUsuario();
        ConAU_CrearUsuario ConCUser = new ConAU_CrearUsuario(CreateUser);
        ConCUser.Inicio();
        
        contentAU.removeAll();
        contentAU.add(CreateUser);
        contentAU.revalidate();
        contentAU.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentAU;
    private Vista.components.CustomButton jButton1;
    private Vista.components.CustomButton jButton2;
    private javax.swing.JPanel jPanel1;
    private Vista.utils.PanelRound panelRound2;
    private Vista.utils.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}
