package Vista;
import Vista.utils.UIConfig;

public class AU_BuscarUsuario extends javax.swing.JPanel {

    public AU_BuscarUsuario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanBuscarUsu = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        PanSearchName = new javax.swing.JPanel();
        customLabel1 = new Vista.components.CustomLabel();
        TxtSearchName = new Vista.components.CustomInput();
        PanSearchDoc = new javax.swing.JPanel();
        customLabel2 = new Vista.components.CustomLabel();
        TxtSearchDoc = new Vista.components.CustomInput();
        errorSearch = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        PanApe = new javax.swing.JPanel();
        customLabel3 = new Vista.components.CustomLabel();
        TxtSearchApe = new Vista.components.CustomInput();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Vista.utils.PanelRound();
        BtoBuscar = new Vista.components.CustomButton();

        setBackground(UIConfig.getBg(300)
        );
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        PanBuscarUsu.setOpaque(false);
        PanBuscarUsu.setPreferredSize(new java.awt.Dimension(0, 0));
        PanBuscarUsu.setLayout(new javax.swing.BoxLayout(PanBuscarUsu, javax.swing.BoxLayout.LINE_AXIS));

        LeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 25));
        LeftPanel.setOpaque(false);
        LeftPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        LeftPanel.setLayout(new java.awt.GridLayout(4, 0, 0, 50));

        PanSearchName.setForeground(new java.awt.Color(255, 255, 255));
        PanSearchName.setOpaque(false);
        PanSearchName.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel1.setText("Nombre del Usuario:");
        PanSearchName.add(customLabel1);
        PanSearchName.add(TxtSearchName);

        LeftPanel.add(PanSearchName);

        PanSearchDoc.setOpaque(false);
        PanSearchDoc.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel2.setText("Documento del Usuario:");
        PanSearchDoc.add(customLabel2);
        PanSearchDoc.add(TxtSearchDoc);

        LeftPanel.add(PanSearchDoc);

        errorSearch.setForeground(new java.awt.Color(255, 0, 0));
        LeftPanel.add(errorSearch);

        PanBuscarUsu.add(LeftPanel);

        RightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 25, 50, 50));
        RightPanel.setOpaque(false);
        RightPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        RightPanel.setLayout(new java.awt.GridLayout(4, 0, 0, 50));

        PanApe.setOpaque(false);
        PanApe.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel3.setText("Apellido del Usuario:");
        PanApe.add(customLabel3);
        PanApe.add(TxtSearchApe);

        RightPanel.add(PanApe);

        jPanel1.setOpaque(false);
        RightPanel.add(jPanel1);

        panelRound1.setBackground(UIConfig.getPrimaryColor(300));
        panelRound1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new javax.swing.BoxLayout(panelRound1, javax.swing.BoxLayout.LINE_AXIS));

        BtoBuscar.setText("Buscar");
        BtoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoBuscarActionPerformed(evt);
            }
        });
        panelRound1.add(BtoBuscar);

        RightPanel.add(panelRound1);

        PanBuscarUsu.add(RightPanel);

        add(PanBuscarUsu);
    }// </editor-fold>//GEN-END:initComponents

    private void BtoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtoBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Vista.components.CustomButton BtoBuscar;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel PanApe;
    public javax.swing.JPanel PanBuscarUsu;
    private javax.swing.JPanel PanSearchDoc;
    private javax.swing.JPanel PanSearchName;
    private javax.swing.JPanel RightPanel;
    public Vista.components.CustomInput TxtSearchApe;
    public Vista.components.CustomInput TxtSearchDoc;
    public Vista.components.CustomInput TxtSearchName;
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomLabel customLabel2;
    private Vista.components.CustomLabel customLabel3;
    public javax.swing.JLabel errorSearch;
    private javax.swing.JPanel jPanel1;
    private Vista.utils.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
