package Vista;

import Vista.utils.UIConfig;

public class AU_CrearUsuario extends javax.swing.JPanel {

    public AU_CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        PanNewUserName = new javax.swing.JPanel();
        customLabel1 = new Vista.components.CustomLabel();
        TxtNewUserName = new Vista.components.CustomInput();
        PanNewUserDoc = new javax.swing.JPanel();
        customLabel2 = new Vista.components.CustomLabel();
        TxtNewUserDoc = new Vista.components.CustomInput();
        PanNewUserCorreo = new javax.swing.JPanel();
        customLabel3 = new Vista.components.CustomLabel();
        TxtNewUserCorreo = new Vista.components.CustomInput();
        PanNewUserVin = new javax.swing.JPanel();
        customLabel4 = new Vista.components.CustomLabel();
        BoxNewUserVin = new javax.swing.JComboBox<>();
        ErrorNewUser = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        PanNewUserApe = new javax.swing.JPanel();
        customLabel5 = new Vista.components.CustomLabel();
        TxtNewUserApe = new Vista.components.CustomInput();
        PanNewUserFaculty = new javax.swing.JPanel();
        customLabel6 = new Vista.components.CustomLabel();
        BoxNewUserFaculty = new javax.swing.JComboBox<>();
        PanNewUserCareer = new javax.swing.JPanel();
        customLabel7 = new Vista.components.CustomLabel();
        TxtNewUserCareer = new Vista.components.CustomInput();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Vista.utils.PanelRound();
        BtnaAñadirUsuario = new Vista.components.CustomButton();

        setBackground(UIConfig.getBg(300)
        );
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        LeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 25));
        LeftPanel.setOpaque(false);
        LeftPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        LeftPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 50));

        PanNewUserName.setOpaque(false);
        PanNewUserName.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewUserName.setRequestFocusEnabled(false);
        PanNewUserName.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel1.setText("Nombres del usuario:");
        PanNewUserName.add(customLabel1);
        PanNewUserName.add(TxtNewUserName);

        LeftPanel.add(PanNewUserName);

        PanNewUserDoc.setOpaque(false);
        PanNewUserDoc.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewUserDoc.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel2.setText("Documento del usuario:");
        PanNewUserDoc.add(customLabel2);
        PanNewUserDoc.add(TxtNewUserDoc);

        LeftPanel.add(PanNewUserDoc);

        PanNewUserCorreo.setMinimumSize(new java.awt.Dimension(0, 0));
        PanNewUserCorreo.setOpaque(false);
        PanNewUserCorreo.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel3.setText("Correo del Usuario");
        PanNewUserCorreo.add(customLabel3);
        PanNewUserCorreo.add(TxtNewUserCorreo);

        LeftPanel.add(PanNewUserCorreo);

        PanNewUserVin.setOpaque(false);
        PanNewUserVin.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewUserVin.setLayout(new java.awt.GridLayout(1, 0));

        customLabel4.setText("Vinculacion del Usuario:");
        PanNewUserVin.add(customLabel4);

        BoxNewUserVin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante ", "Funcionari@", "Contratista", "Egresad@" }));
        BoxNewUserVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNewUserVinActionPerformed(evt);
            }
        });
        PanNewUserVin.add(BoxNewUserVin);

        LeftPanel.add(PanNewUserVin);

        ErrorNewUser.setForeground(new java.awt.Color(255, 51, 51));
        LeftPanel.add(ErrorNewUser);

        add(LeftPanel);

        RightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 25, 50, 50));
        RightPanel.setOpaque(false);
        RightPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        RightPanel.setRequestFocusEnabled(false);
        RightPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 50));

        PanNewUserApe.setOpaque(false);
        PanNewUserApe.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewUserApe.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel5.setText("Apellidos del usuario:");
        PanNewUserApe.add(customLabel5);
        PanNewUserApe.add(TxtNewUserApe);

        RightPanel.add(PanNewUserApe);

        PanNewUserFaculty.setOpaque(false);
        PanNewUserFaculty.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewUserFaculty.setLayout(new java.awt.GridLayout(1, 0));

        customLabel6.setText("Facultad del Usuario:");
        PanNewUserFaculty.add(customLabel6);

        BoxNewUserFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artes", "Ciencias", "Ciencias Agrarias", "Ciencias Economicas", "Ciencias Humanas", "Derecho, Ciencias Politicas y Sociales", "Enfermeria", "Ingenieria", "Medicina", "Medicina Veterinaria y Zootecnia", "Odontologia" }));
        PanNewUserFaculty.add(BoxNewUserFaculty);

        RightPanel.add(PanNewUserFaculty);

        PanNewUserCareer.setOpaque(false);
        PanNewUserCareer.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewUserCareer.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel7.setText("Carrera del Usuario:");
        PanNewUserCareer.add(customLabel7);
        PanNewUserCareer.add(TxtNewUserCareer);

        RightPanel.add(PanNewUserCareer);

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        RightPanel.add(jPanel1);

        panelRound1.setBackground(UIConfig.getPrimaryColor(300));
        panelRound1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new javax.swing.BoxLayout(panelRound1, javax.swing.BoxLayout.LINE_AXIS));

        BtnaAñadirUsuario.setText("Añadir");
        panelRound1.add(BtnaAñadirUsuario);

        RightPanel.add(panelRound1);

        add(RightPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void BoxNewUserVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNewUserVinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNewUserVinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> BoxNewUserFaculty;
    public javax.swing.JComboBox<String> BoxNewUserVin;
    public Vista.components.CustomButton BtnaAñadirUsuario;
    public javax.swing.JLabel ErrorNewUser;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel PanNewUserApe;
    private javax.swing.JPanel PanNewUserCareer;
    private javax.swing.JPanel PanNewUserCorreo;
    private javax.swing.JPanel PanNewUserDoc;
    private javax.swing.JPanel PanNewUserFaculty;
    private javax.swing.JPanel PanNewUserName;
    private javax.swing.JPanel PanNewUserVin;
    private javax.swing.JPanel RightPanel;
    public Vista.components.CustomInput TxtNewUserApe;
    public Vista.components.CustomInput TxtNewUserCareer;
    public Vista.components.CustomInput TxtNewUserCorreo;
    public Vista.components.CustomInput TxtNewUserDoc;
    public Vista.components.CustomInput TxtNewUserName;
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomLabel customLabel2;
    private Vista.components.CustomLabel customLabel3;
    private Vista.components.CustomLabel customLabel4;
    private Vista.components.CustomLabel customLabel5;
    private Vista.components.CustomLabel customLabel6;
    private Vista.components.CustomLabel customLabel7;
    private javax.swing.JPanel jPanel1;
    private Vista.utils.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
