package Vista;

import org.json.JSONObject;
import Vista.utils.UIConfig;
        
public class AU_InfoUsuario extends javax.swing.JPanel {


    public AU_InfoUsuario(JSONObject findUser) {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInfo = new javax.swing.JPanel();
        PanInfoName = new javax.swing.JPanel();
        customLabel1 = new Vista.components.CustomLabel();
        ShowUserName = new Vista.components.CustomInput();
        PanInfoDocument = new javax.swing.JPanel();
        customLabel2 = new Vista.components.CustomLabel();
        ShowUserDoc = new Vista.components.CustomInput();
        PanInfoExtra = new javax.swing.JPanel();
        customLabel3 = new Vista.components.CustomLabel();
        ShowUserOtherInfo = new Vista.components.CustomInput();
        ErrorUserNotFound = new javax.swing.JLabel();

        setBackground(UIConfig.getBg(300)
        );
        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        PanelInfo.setOpaque(false);
        PanelInfo.setPreferredSize(new java.awt.Dimension(0, 0));
        PanelInfo.setLayout(new java.awt.GridLayout(4, 0, 0, 50));

        PanInfoName.setMinimumSize(new java.awt.Dimension(0, 0));
        PanInfoName.setOpaque(false);
        PanInfoName.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel1.setText("Nombre del usuario:");
        PanInfoName.add(customLabel1);
        PanInfoName.add(ShowUserName);

        PanelInfo.add(PanInfoName);

        PanInfoDocument.setOpaque(false);
        PanInfoDocument.setPreferredSize(new java.awt.Dimension(0, 0));
        PanInfoDocument.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel2.setText("Documento del usuario: ");
        PanInfoDocument.add(customLabel2);
        PanInfoDocument.add(ShowUserDoc);

        PanelInfo.add(PanInfoDocument);

        PanInfoExtra.setOpaque(false);
        PanInfoExtra.setPreferredSize(new java.awt.Dimension(0, 0));
        PanInfoExtra.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel3.setText("Información extra del usuario:");
        PanInfoExtra.add(customLabel3);
        PanInfoExtra.add(ShowUserOtherInfo);

        PanelInfo.add(PanInfoExtra);

        ErrorUserNotFound.setForeground(new java.awt.Color(255, 0, 0));
        PanelInfo.add(ErrorUserNotFound);

        add(PanelInfo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ErrorUserNotFound;
    private javax.swing.JPanel PanInfoDocument;
    private javax.swing.JPanel PanInfoExtra;
    private javax.swing.JPanel PanInfoName;
    private javax.swing.JPanel PanelInfo;
    public Vista.components.CustomInput ShowUserDoc;
    public Vista.components.CustomInput ShowUserName;
    public Vista.components.CustomInput ShowUserOtherInfo;
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomLabel customLabel2;
    private Vista.components.CustomLabel customLabel3;
    // End of variables declaration//GEN-END:variables
}
