/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Vista.utils.UIConfig;

public class CrearCorresponsabilidad extends javax.swing.JPanel {

    /**
     * Creates new form CrearCorresponsabilidad
     */
    public CrearCorresponsabilidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        PanNewCorName = new javax.swing.JPanel();
        customLabel1 = new Vista.components.CustomLabel();
        TxtNewCorName = new Vista.components.CustomInput();
        PanNewCorDoc = new javax.swing.JPanel();
        customLabel2 = new Vista.components.CustomLabel();
        TxtNewCorDoc = new Vista.components.CustomInput();
        PanNewCorCorreo = new javax.swing.JPanel();
        customLabel3 = new Vista.components.CustomLabel();
        TxtNewCorCorreo = new Vista.components.CustomInput();
        PanNewCorTime = new javax.swing.JPanel();
        customLabel4 = new Vista.components.CustomLabel();
        TxtNewCorTime = new Vista.components.CustomInput();
        ErrorNewCor = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        PanNewCorApe = new javax.swing.JPanel();
        customLabel5 = new Vista.components.CustomLabel();
        TxtNewCorApe = new Vista.components.CustomInput();
        PanNewCorFaculty = new javax.swing.JPanel();
        customLabel7 = new Vista.components.CustomLabel();
        BoxNewCorFaculty = new javax.swing.JComboBox<>();
        PanNewCorCareer = new javax.swing.JPanel();
        customLabel6 = new Vista.components.CustomLabel();
        TxtNewCorCareer = new Vista.components.CustomInput();
        jPanel4 = new javax.swing.JPanel();
        panelRound1 = new Vista.utils.PanelRound();
        BtnaAñadirCorresponsabilidad = new Vista.components.CustomButton();

        setBackground(UIConfig.getBg(300));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        LeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 25));
        LeftPanel.setOpaque(false);
        LeftPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        LeftPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 50));

        PanNewCorName.setOpaque(false);
        PanNewCorName.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewCorName.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel1.setText("Nombres Del Estudiante:");
        PanNewCorName.add(customLabel1);
        PanNewCorName.add(TxtNewCorName);

        LeftPanel.add(PanNewCorName);

        PanNewCorDoc.setMinimumSize(new java.awt.Dimension(0, 0));
        PanNewCorDoc.setOpaque(false);
        PanNewCorDoc.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewCorDoc.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel2.setText("Documento Del Estudiante:");
        PanNewCorDoc.add(customLabel2);
        PanNewCorDoc.add(TxtNewCorDoc);

        LeftPanel.add(PanNewCorDoc);

        PanNewCorCorreo.setMinimumSize(new java.awt.Dimension(0, 0));
        PanNewCorCorreo.setOpaque(false);
        PanNewCorCorreo.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewCorCorreo.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel3.setText("Correo Del Estudiante:");
        PanNewCorCorreo.add(customLabel3);
        PanNewCorCorreo.add(TxtNewCorCorreo);

        LeftPanel.add(PanNewCorCorreo);

        PanNewCorTime.setOpaque(false);
        PanNewCorTime.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewCorTime.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel4.setText("Tiempo De Corresponsabilidad Del Estudiante:");
        PanNewCorTime.add(customLabel4);
        PanNewCorTime.add(TxtNewCorTime);

        LeftPanel.add(PanNewCorTime);
        LeftPanel.add(ErrorNewCor);

        add(LeftPanel);

        RightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 25, 50, 50));
        RightPanel.setOpaque(false);
        RightPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        RightPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 50));

        PanNewCorApe.setOpaque(false);
        PanNewCorApe.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewCorApe.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel5.setText("Apellidos Del Estudiante:");
        PanNewCorApe.add(customLabel5);
        PanNewCorApe.add(TxtNewCorApe);

        RightPanel.add(PanNewCorApe);

        PanNewCorFaculty.setOpaque(false);
        PanNewCorFaculty.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewCorFaculty.setLayout(new java.awt.GridLayout(1, 0, 0, 10));

        customLabel7.setText("Facultad Del Estudiante:");
        PanNewCorFaculty.add(customLabel7);

        BoxNewCorFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artes", "Ciencias", "Ciencias Agrarias", "Ciencias Economicas", "Ciencias Humanas", "Derecho, Ciencias Politicas y Sociales", "Enfermeria", "Ingenieria", "Medicina", "Medicina Veterinaria y Zootecnia", "Odontologia" }));
        PanNewCorFaculty.add(BoxNewCorFaculty);

        RightPanel.add(PanNewCorFaculty);

        PanNewCorCareer.setOpaque(false);
        PanNewCorCareer.setPreferredSize(new java.awt.Dimension(0, 0));
        PanNewCorCareer.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        customLabel6.setText("Carrera del Estudiante:");
        PanNewCorCareer.add(customLabel6);
        PanNewCorCareer.add(TxtNewCorCareer);

        RightPanel.add(PanNewCorCareer);

        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        RightPanel.add(jPanel4);

        panelRound1.setBackground(UIConfig.getPrimaryColor(300)
        );
        panelRound1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new javax.swing.BoxLayout(panelRound1, javax.swing.BoxLayout.LINE_AXIS));

        BtnaAñadirCorresponsabilidad.setText("Generar Estudiante");
        panelRound1.add(BtnaAñadirCorresponsabilidad);

        RightPanel.add(panelRound1);

        add(RightPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> BoxNewCorFaculty;
    public Vista.components.CustomButton BtnaAñadirCorresponsabilidad;
    public javax.swing.JLabel ErrorNewCor;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel PanNewCorApe;
    private javax.swing.JPanel PanNewCorCareer;
    private javax.swing.JPanel PanNewCorCorreo;
    private javax.swing.JPanel PanNewCorDoc;
    private javax.swing.JPanel PanNewCorFaculty;
    private javax.swing.JPanel PanNewCorName;
    private javax.swing.JPanel PanNewCorTime;
    private javax.swing.JPanel RightPanel;
    public Vista.components.CustomInput TxtNewCorApe;
    public Vista.components.CustomInput TxtNewCorCareer;
    public Vista.components.CustomInput TxtNewCorCorreo;
    public Vista.components.CustomInput TxtNewCorDoc;
    public Vista.components.CustomInput TxtNewCorName;
    public Vista.components.CustomInput TxtNewCorTime;
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomLabel customLabel2;
    private Vista.components.CustomLabel customLabel3;
    private Vista.components.CustomLabel customLabel4;
    private Vista.components.CustomLabel customLabel5;
    private Vista.components.CustomLabel customLabel6;
    private Vista.components.CustomLabel customLabel7;
    private javax.swing.JPanel jPanel4;
    private Vista.utils.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
