package Vista;
import Modelo.Sala;
import Modelo.Servicio;
import Vista.components.CreateComputers;
import Vista.utils.UIConfig;
import java.util.Map;
import org.json.JSONObject;

public class CreateSala extends javax.swing.JPanel {

    private final Aplication JFP;
    public CreateSala(Aplication JFP) {
        this.JFP = JFP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        gridPanelSala = new Vista.components.GridPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        customLabel2 = new Vista.components.CustomLabel();
        cols = new Vista.components.CustomInput();
        customLabel1 = new Vista.components.CustomLabel();
        rows = new Vista.components.CustomInput();
        updateSize = new Vista.components.CustomButton();
        customLabel3 = new Vista.components.CustomLabel();
        name = new Vista.components.CustomInput();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cancel = new Vista.components.CustomButton("Cancelar", 2);
        create = new Vista.components.CustomButton("Crear",1);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());
        jPanel2.add(gridPanelSala, new java.awt.GridBagConstraints());

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(UIConfig.getBg(300));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 1, 50, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(250, 350));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 500));

        customLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customLabel2.setText("Columnas:");
        customLabel2.setMaximumSize(new java.awt.Dimension(300, 20));
        customLabel2.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel4.add(customLabel2);

        cols.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel4.add(cols);

        customLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customLabel1.setText("Filas:");
        customLabel1.setMaximumSize(new java.awt.Dimension(300, 20));
        customLabel1.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel4.add(customLabel1);

        rows.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel4.add(rows);

        updateSize.setText("Actualizar");
        updateSize.setPreferredSize(new java.awt.Dimension(200, 40));
        updateSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSizeActionPerformed(evt);
            }
        });
        jPanel4.add(updateSize);

        customLabel3.setText("Nombre de la Sala");
        jPanel4.add(customLabel3);

        name.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel4.add(name);

        jLabel1.setText(" ");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 16));
        jPanel4.add(jLabel1);

        jLabel2.setText(" ");
        jLabel2.setMaximumSize(new java.awt.Dimension(300, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 16));
        jPanel4.add(jLabel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        cancel.setText("Cancelar");
        cancel.setStyle(2);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel3.add(cancel);

        create.setText("Crear");
        create.setStyle(1);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel3.add(create);

        jPanel4.add(jPanel3);

        jPanel1.add(jPanel4, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void updateSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSizeActionPerformed
        if (!cols.getText().isEmpty()){
            gridPanelSala.setCols(Integer.parseInt(cols.getText()));
        }
        if (!rows.getText().isEmpty()){
            gridPanelSala.setRows(Integer.parseInt(rows.getText()));
        }
    }//GEN-LAST:event_updateSizeActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        ViewSalas vs = new ViewSalas(JFP);
        JFP.changeContent(vs);
    }//GEN-LAST:event_cancelActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        if(!name.getText().isEmpty()){
            Map<Integer, int[]> computersData = gridPanelSala.getClickedPoints();
            Sala createdRoom = Servicio.createRoom(name.getText(), gridPanelSala.getRows(), gridPanelSala.getCols(), computersData);
            CreateComputers cc = new CreateComputers(computersData, createdRoom, JFP);
            JFP.changeContent(cc);
        }
    }//GEN-LAST:event_createActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.components.CustomButton cancel;
    private Vista.components.CustomInput cols;
    private Vista.components.CustomButton create;
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomLabel customLabel2;
    private Vista.components.CustomLabel customLabel3;
    private Vista.components.GridPanel gridPanelSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private Vista.components.CustomInput name;
    private Vista.components.CustomInput rows;
    private Vista.components.CustomButton updateSize;
    // End of variables declaration//GEN-END:variables
}
