package Vista;

import Modelo.Computador;
import Modelo.Sala;
import Modelo.Servicio;
import Modelo.Sesion;
import Modelo.Users.Usuario;
import Vista.components.CustomButton;
import Vista.components.GridLabelPanel;
import Vista.components.ModalAddUser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import Vista.utils.UIConfig;
import java.awt.BorderLayout;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 *
 * @author layonel
 */
public class ManagmentSala extends javax.swing.JPanel {
    private Sala sala;
    private Map<Integer, Computador> formatedCompu;
    private HashMap<Integer, Sesion> formatedSession;
    private Computador selectedComputed;

    public ManagmentSala(Sala sala) {
        this.sala = sala;
        Map<Integer, int[]> iconPositions = sala.getComputers_arrays();
        Computador computers[] = Servicio.getComputers(sala.getId());
        formatedCompu = new HashMap<>();
        for (Computador comp : computers){
            System.out.println(comp.getCont_sala());
            formatedCompu.put(comp.getCont_sala(), comp);
        }       
        updateSessions();
        initComponents();
        salaName.setText(sala.getName());
        generateGrid(iconPositions);
    }
    
    public void updateSessions (){
        Sesion active_sessions[] = Servicio.getActiveSessions(sala);
        this.formatedSession = new HashMap<>();
        
        for (Sesion session: active_sessions){
            this.formatedSession.put(session.getComputador().getCont_sala(), session);
        }
    }
    
    public void update(){
        updateSessions();
        computerState.setText("");
        addButton.setEnabled(true);
        clearButton.setEnabled(false);
        sessionName.setText("");
        this.refresh();
        this.revalidate();
        this.repaint();
    }
    
    public void generateGrid (Map<Integer, int[]> iconPositions){
        iconPositions.put(1, new int[]{1, 1});
        iconPositions.put(2, new int[]{2, 2});

        GridLabelPanel gridLabelPanel = new GridLabelPanel( sala.getRows(), sala.getCols(), iconPositions);

        content.add(gridLabelPanel, BorderLayout.CENTER);
        content.setVisible(true);
        
        gridLabelPanel.setIconClickListener(key -> {
            computerName.setText(formatedCompu.get(key).getName());
            this.selectedComputed = formatedCompu.get(key);
            System.out.println("Se hizo clic en el JLabel con la clave: " + key);
            if (formatedSession.containsKey(key)){
                computerState.setText("OCUPADO");
                addButton.setEnabled(false);
                clearButton.setEnabled(true);
                Sesion currentSession = formatedSession.get(key);
                sessionName.setText(currentSession.getUsuario().getName());
            }else{
                computerState.setText("LIBRE");
                addButton.setEnabled(true);
                clearButton.setEnabled(false);
                sessionName.setText("");
            }
        });
    }
    
    public void refresh(){
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTabla = new javax.swing.JPopupMenu();
        salaName = new Vista.components.Title();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        customLabel1 = new Vista.components.CustomLabel();
        computerName = new Vista.components.CustomInput();
        customLabel2 = new Vista.components.CustomLabel();
        computerState = new Vista.components.CustomInput();
        customLabel3 = new Vista.components.CustomLabel();
        sessionName = new Vista.components.CustomInput();
        clearButton = new Vista.components.CustomButton("Limpiar", 2);
        addButton = new Vista.components.CustomButton("Añadir Usuario",1);
        content = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        salaName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salaName.setText("Name Sala");
        salaName.setAlignmentX(0.5F);
        salaName.setPreferredSize(new java.awt.Dimension(101, 30));
        add(salaName, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 0));
        jPanel2.setLayout(new java.awt.GridLayout(10, 2, 0, 5));

        customLabel1.setText("Nombre del Computador: ");
        jPanel2.add(customLabel1);
        jPanel2.add(computerName);

        customLabel2.setText("Estado Actual:");
        jPanel2.add(customLabel2);
        jPanel2.add(computerState);

        customLabel3.setText("Nombre Persona: ");
        jPanel2.add(customLabel3);
        jPanel2.add(sessionName);

        clearButton.setText("Limpiar");
        clearButton.setStyle(2);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(clearButton);

        addButton.setText("Añadir Usuario");
        addButton.setStyle(1);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(content, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        Servicio.deleteActiveSession(selectedComputed.getId(), sala.getId());
        update();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        System.out.println("Se obtubo la seleccion");
        Object id = selectedComputed.getId();

        Integer sala_id = sala.getId();
        System.out.println(sala_id);
        ModalAddUser modalNewUser = new ModalAddUser(id, sala_id, this);
        modalNewUser.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.components.CustomButton addButton;
    private Vista.components.CustomButton clearButton;
    private Vista.components.CustomInput computerName;
    private Vista.components.CustomInput computerState;
    private javax.swing.JPanel content;
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomLabel customLabel2;
    private Vista.components.CustomLabel customLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu menuTabla;
    private Vista.components.Title salaName;
    private Vista.components.CustomInput sessionName;
    // End of variables declaration//GEN-END:variables
}
