package Vista;

import Modelo.Computador;
import Modelo.Sala;
import Modelo.Servicio;
import Modelo.Sesion;
import Vista.components.GridLabelPanel;
import Vista.components.ModalAddUser;
import java.util.HashMap;
import java.awt.BorderLayout;
import java.util.Map;

public class ManagmentSala extends javax.swing.JPanel {
    private Sala sala;
    private Map<Integer, Computador> formatedCompu;
    private HashMap<Integer, Sesion> formatedSession;
    private Computador selectedComputed;
    public Aplication JFPrincipal;
    private GridLabelPanel glp;

    public ManagmentSala(Sala sala, Aplication JFPrincipal) {
        this.JFPrincipal = JFPrincipal;
        this.sala = sala;
        Map<Integer, int[]> iconPositions = sala.getComputers_arrays();
        Computador computers[] = Servicio.getComputers(sala.getId());
        formatedCompu = new HashMap<>();
        for (Computador comp : computers){
            formatedCompu.put(comp.getCont_sala(), comp);
        }       
        updateSessions();
        initComponents();
        salaName.setText(sala.getName());
        generateGrid(iconPositions);
    }
    
    public void updateSessions (){
        Sesion active_sessions[] = Servicio.getActiveSessions(sala);
        this.formatedSession = new HashMap<>();
        
        for (Sesion session: active_sessions){
            this.formatedSession.put(session.getComputador().getCont_sala(), session);
        }
    }
    
    public void update(){
        updateSessions();
        computerState.setText("");
        computerName.setText("");
        addButton.setEnabled(false);
        clearButton.setEnabled(false);
        name.setText("");
        career.setText("");
        this.refresh();
        glp.clearSelections();
        glp.updateIcons(formatedSession);
    }
    
    public void generateGrid (Map<Integer, int[]> iconPositions){
        GridLabelPanel gridLabelPanel = new GridLabelPanel( sala.getRows(), sala.getCols(), iconPositions, formatedSession);
        this.glp = gridLabelPanel;
        content.add(gridLabelPanel, BorderLayout.CENTER);
        content.setVisible(true);
        
        gridLabelPanel.setIconClickListener(key -> {
            computerName.setText(formatedCompu.get(key).getName());
            this.selectedComputed = formatedCompu.get(key);
            if (formatedSession.containsKey(key)){
                computerState.setText("OCUPADO");
                addButton.setEnabled(false);
                clearButton.setEnabled(true);
                Sesion currentSession = formatedSession.get(key);
                name.setText(currentSession.getUsuario().getName() + " " + currentSession.getUsuario().getLast_name());
                career.setText(currentSession.getUsuario().getCareer());
            }else{
                computerState.setText("LIBRE");
                addButton.setEnabled(true);
                clearButton.setEnabled(false);
                name.setText("");
            }
        });
    }
    
    public void refresh(){
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salaName = new Vista.components.Title();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        customLabel1 = new Vista.components.CustomLabel();
        computerName = new Vista.components.CustomLabel();
        customLabel2 = new Vista.components.CustomLabel();
        computerState = new Vista.components.CustomLabel();
        customLabel3 = new Vista.components.CustomLabel();
        name = new Vista.components.CustomLabel();
        customLabel4 = new Vista.components.CustomLabel();
        career = new Vista.components.CustomLabel();
        gridLabelPanel1 = new Vista.components.GridLabelPanel();
        gridLabelPanel2 = new Vista.components.GridLabelPanel();
        clearButton = new Vista.components.CustomButton("Limpiar", 2);
        addButton = new Vista.components.CustomButton("Añadir Usuario",1);
        customLabel5 = new Vista.components.CustomLabel();
        customLabel6 = new Vista.components.CustomLabel();
        content = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        setFocusable(false);
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        salaName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salaName.setText("Name Sala");
        salaName.setAlignmentX(0.5F);
        salaName.setPreferredSize(new java.awt.Dimension(101, 30));
        add(salaName, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 0));
        jPanel2.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        customLabel1.setText("Nombre del Computador: ");
        customLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(customLabel1);

        computerName.setText(" ");
        jPanel2.add(computerName);

        customLabel2.setText("Estado Actual:");
        customLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(customLabel2);

        computerState.setText(" ");
        jPanel2.add(computerState);

        customLabel3.setText("Nombre: ");
        customLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(customLabel3);

        name.setText(" ");
        jPanel2.add(name);

        customLabel4.setText("Carrera:");
        customLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(customLabel4);

        career.setText(" ");
        jPanel2.add(career);
        jPanel2.add(gridLabelPanel1);
        jPanel2.add(gridLabelPanel2);

        clearButton.setText("Limpiar");
        clearButton.setStyle(2);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(clearButton);

        addButton.setText("Añadir Usuario");
        addButton.setStyle(1);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton);
        jPanel2.add(customLabel5);
        jPanel2.add(customLabel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        content.setFocusable(false);
        content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(content, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        Servicio.deleteActiveSession(selectedComputed.getId(), sala.getId());
        update();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Object id = selectedComputed.getId();

        Integer sala_id = sala.getId();
        System.out.println(sala_id);
        ModalAddUser modalNewUser = new ModalAddUser(id, sala_id, this);
        modalNewUser.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.components.CustomButton addButton;
    private Vista.components.CustomLabel career;
    private Vista.components.CustomButton clearButton;
    private Vista.components.CustomLabel computerName;
    private Vista.components.CustomLabel computerState;
    private javax.swing.JPanel content;
    private Vista.components.CustomLabel customLabel1;
    private Vista.components.CustomLabel customLabel2;
    private Vista.components.CustomLabel customLabel3;
    private Vista.components.CustomLabel customLabel4;
    private Vista.components.CustomLabel customLabel5;
    private Vista.components.CustomLabel customLabel6;
    private Vista.components.GridLabelPanel gridLabelPanel1;
    private Vista.components.GridLabelPanel gridLabelPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private Vista.components.CustomLabel name;
    private Vista.components.Title salaName;
    // End of variables declaration//GEN-END:variables
}
