package Vista;
import Vista.utils.UIConfig;

public class VistaEstadisticas extends javax.swing.JPanel {

    public VistaEstadisticas() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tituloVistaAnaliticas = new javax.swing.JPanel();
        panelSeleccionSala = new javax.swing.JPanel();
        comboBoxSelecciónSala = new javax.swing.JComboBox<>();
        panelFechaInicio = new javax.swing.JPanel();
        fechaInicialDateChooser = new com.toedter.calendar.JDateChooser();
        panelFechaFinal = new javax.swing.JPanel();
        fechaFinalDateChooser = new com.toedter.calendar.JDateChooser();
        panelSeleccionVisualización = new javax.swing.JPanel();
        comboBoxSeleccionVisualizacion = new javax.swing.JComboBox<>();
        panelCentral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelSolicitaRango = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelSolicitaSala = new javax.swing.JPanel();
        panelGenerarGrafico = new javax.swing.JPanel();
        panelSeleccionTipoGrafico = new javax.swing.JPanel();
        comboBoxSeleccionTipoGrafico = new javax.swing.JComboBox<>();
        panelRound1 = new Vista.utils.PanelRound();
        buttonGenerarGrafico = new Vista.components.CustomButton();

        setBackground(UIConfig.getBg(100));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new java.awt.BorderLayout());

        tituloVistaAnaliticas.setBackground(UIConfig.getBg(300));
        tituloVistaAnaliticas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tituloVistaAnaliticas.setPreferredSize(new java.awt.Dimension(0, 55));
        tituloVistaAnaliticas.setLayout(new java.awt.GridLayout(1, 5));

        panelSeleccionSala.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sala : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, UIConfig.generateFontBySize(UIConfig.text_sm)
            , UIConfig.getForeground()));
    panelSeleccionSala.setOpaque(false);
    panelSeleccionSala.setLayout(new java.awt.GridLayout(1, 0));

    comboBoxSelecciónSala.setFont(UIConfig.generateFontBySize(UIConfig.text_sm));
    comboBoxSelecciónSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    comboBoxSelecciónSala.setToolTipText("hola");
    comboBoxSelecciónSala.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboBoxSelecciónSalaActionPerformed(evt);
        }
    });
    panelSeleccionSala.add(comboBoxSelecciónSala);

    tituloVistaAnaliticas.add(panelSeleccionSala);

    panelFechaInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha Inicial : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, UIConfig.generateFontBySize(UIConfig.text_sm), UIConfig.getForeground()));
    panelFechaInicio.setOpaque(false);
    panelFechaInicio.setLayout(new java.awt.GridLayout(1, 0));

    fechaInicialDateChooser.setFont(UIConfig.generateFontBySize(UIConfig.text_sm));
    panelFechaInicio.add(fechaInicialDateChooser);

    tituloVistaAnaliticas.add(panelFechaInicio);

    panelFechaFinal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha Final : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, UIConfig.generateFontBySize(UIConfig.text_sm), UIConfig.getForeground()));
    panelFechaFinal.setOpaque(false);
    panelFechaFinal.setLayout(new java.awt.GridLayout(1, 0));

    fechaFinalDateChooser.setFont(UIConfig.generateFontBySize(UIConfig.text_sm));
    panelFechaFinal.add(fechaFinalDateChooser);

    tituloVistaAnaliticas.add(panelFechaFinal);

    panelSeleccionVisualización.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Visualización : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, UIConfig.generateFontBySize(UIConfig.text_sm), UIConfig.getForeground()));
    panelSeleccionVisualización.setOpaque(false);
    panelSeleccionVisualización.setLayout(new java.awt.GridLayout(1, 0));

    comboBoxSeleccionVisualizacion.setFont(UIConfig.generateFontBySize(UIConfig.text_sm));
    comboBoxSeleccionVisualizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "Meses", "Días del Año" }));
    comboBoxSeleccionVisualizacion.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboBoxSeleccionVisualizacionActionPerformed(evt);
        }
    });
    panelSeleccionVisualización.add(comboBoxSeleccionVisualizacion);

    tituloVistaAnaliticas.add(panelSeleccionVisualización);

    add(tituloVistaAnaliticas, java.awt.BorderLayout.PAGE_START);

    panelCentral.setBackground(UIConfig.getBg(300));
    panelCentral.setLayout(new javax.swing.BoxLayout(panelCentral, javax.swing.BoxLayout.X_AXIS));

    jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
    jPanel2.setLayout(new java.awt.BorderLayout());

    panelSolicitaRango.setBackground(UIConfig.getBg(100));
    panelSolicitaRango.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    panelSolicitaRango.setPreferredSize(new java.awt.Dimension(0, 0));
    panelSolicitaRango.setLayout(new javax.swing.BoxLayout(panelSolicitaRango, javax.swing.BoxLayout.LINE_AXIS));
    jPanel2.add(panelSolicitaRango, java.awt.BorderLayout.CENTER);

    panelCentral.add(jPanel2);

    jPanel3.setLayout(new java.awt.BorderLayout());

    panelSolicitaSala.setBackground(UIConfig.getBg(100));
    panelSolicitaSala.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    panelSolicitaSala.setPreferredSize(new java.awt.Dimension(0, 0));
    panelSolicitaSala.setLayout(new javax.swing.BoxLayout(panelSolicitaSala, javax.swing.BoxLayout.LINE_AXIS));
    jPanel3.add(panelSolicitaSala, java.awt.BorderLayout.CENTER);
    panelSolicitaSala.getAccessibleContext().setAccessibleName("");

    panelCentral.add(jPanel3);

    add(panelCentral, java.awt.BorderLayout.CENTER);

    panelGenerarGrafico.setBackground(UIConfig.getBg(300));
    panelGenerarGrafico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    panelGenerarGrafico.setPreferredSize(new java.awt.Dimension(0, 60));
    panelGenerarGrafico.setLayout(new java.awt.GridLayout(1, 0));

    panelSeleccionTipoGrafico.setBackground(UIConfig.getBg(300));
    panelSeleccionTipoGrafico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Gráfico : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, UIConfig.generateFontBySize(UIConfig.text_sm), UIConfig.getForeground()));
    panelSeleccionTipoGrafico.setPreferredSize(new java.awt.Dimension(0, 30));
    panelSeleccionTipoGrafico.setLayout(new java.awt.GridLayout(1, 0));

    comboBoxSeleccionTipoGrafico.setFont(UIConfig.generateFontBySize(UIConfig.text_sm));
    comboBoxSeleccionTipoGrafico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gráfico de Barras", "Gráfico de Líneas" }));
    comboBoxSeleccionTipoGrafico.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboBoxSeleccionTipoGraficoActionPerformed(evt);
        }
    });
    panelSeleccionTipoGrafico.add(comboBoxSeleccionTipoGrafico);

    panelGenerarGrafico.add(panelSeleccionTipoGrafico);

    panelRound1.setLayout(new java.awt.GridLayout(1, 0));

    buttonGenerarGrafico.setText("Generar Gráfico");
    buttonGenerarGrafico.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonGenerarGraficoActionPerformed(evt);
        }
    });
    panelRound1.add(buttonGenerarGrafico);

    panelGenerarGrafico.add(panelRound1);

    add(panelGenerarGrafico, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSelecciónSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSelecciónSalaActionPerformed

    }//GEN-LAST:event_comboBoxSelecciónSalaActionPerformed

    private void comboBoxSeleccionVisualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSeleccionVisualizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSeleccionVisualizacionActionPerformed

    private void comboBoxSeleccionTipoGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSeleccionTipoGraficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSeleccionTipoGraficoActionPerformed

    private void buttonGenerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarGraficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGenerarGraficoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Vista.components.CustomButton buttonGenerarGrafico;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> comboBoxSeleccionTipoGrafico;
    public javax.swing.JComboBox<String> comboBoxSeleccionVisualizacion;
    public javax.swing.JComboBox<String> comboBoxSelecciónSala;
    public com.toedter.calendar.JDateChooser fechaFinalDateChooser;
    public com.toedter.calendar.JDateChooser fechaInicialDateChooser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelFechaFinal;
    private javax.swing.JPanel panelFechaInicio;
    private javax.swing.JPanel panelGenerarGrafico;
    private Vista.utils.PanelRound panelRound1;
    private javax.swing.JPanel panelSeleccionSala;
    private javax.swing.JPanel panelSeleccionTipoGrafico;
    private javax.swing.JPanel panelSeleccionVisualización;
    public javax.swing.JPanel panelSolicitaRango;
    public javax.swing.JPanel panelSolicitaSala;
    private javax.swing.JPanel tituloVistaAnaliticas;
    // End of variables declaration//GEN-END:variables
}
