package Vista;



public class VistaGraficoMeses extends javax.swing.JPanel {


    public VistaGraficoMeses() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGraficoMes = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelGraficoMes.setBackground(new java.awt.Color(255, 255, 255));
        panelGraficoMes.setLayout(new javax.swing.BoxLayout(panelGraficoMes, javax.swing.BoxLayout.LINE_AXIS));
        add(panelGraficoMes);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel panelGraficoMes;
    // End of variables declaration//GEN-END:variables
}
