/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Lenovo
 */
public class VistaGraficoFacultades extends javax.swing.JPanel {

    /**
     * Creates new form VistaGraficoFacultades
     */
    public VistaGraficoFacultades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGraficoFacultades = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        panelGraficoFacultades.setLayout(new javax.swing.BoxLayout(panelGraficoFacultades, javax.swing.BoxLayout.LINE_AXIS));
        add(panelGraficoFacultades);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel panelGraficoFacultades;
    // End of variables declaration//GEN-END:variables
}
